# Generated by Django 3.1.3 on 2022-07-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20220704_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='dosage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicines',
            name='medicine_type',
            field=models.CharField(choices=[('PILLS', 'PILLS'), ('TABLET', 'TABLET'), ('INJECTION', 'INJECTION'), ('SYRUP', 'SYRUP')], default='PILLS', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='time_slot',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BREAK FAST'), (2, 'LUNCH'), (3, 'DINNER')], default=1),
        ),
    ]
