# Generated by Django 3.1.3 on 2022-07-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_auto_20220716_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='capsules',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='track_medicine',
            name='track_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
