# Generated by Django 3.1.3 on 2022-07-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_auto_20220719_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_prescription',
            name='send_on',
            field=models.TimeField(),
        ),
    ]
