# Generated by Django 3.1.3 on 2022-09-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_auto_20220719_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_id',
            new_name='d_id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='doctor',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='works_in',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
