# Generated by Django 3.1.3 on 2022-09-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_auto_20220917_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='comments',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
